# Generated by Django 5.0.6 on 2025-02-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_plato_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
