# Generated by Django 5.0.6 on 2025-02-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_pago_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
