# Generated by Django 5.0.6 on 2025-02-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado_mesa',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada')], default='disponible', max_length=40),
        ),
    ]
