# Generated by Django 5.0.6 on 2025-02-20 14:29

import django.db.models.deletion
from django.db import migrations, models

def create_default_categoria(apps, schema_editor):
    Categoria = apps.get_model('inicio', 'Categoria')
    default_categoria = Categoria(id=1, nombre='Default')
    default_categoria.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_mesa_estado_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=models.CASCADE, related_name='platos', to='inicio.Categoria'),
            preserve_default=False,
        ),
        migrations.RunPython(create_default_categoria),
    ]
