# Generated by Django 5.0.6 on 2025-02-24 00:10

import inicio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_alter_categoria_id_alter_plato_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cedula',
            field=models.CharField(default=0, max_length=10, unique=True, validators=[inicio.models.validate_cedula]),
            preserve_default=False,
        ),
    ]
