# Generated by Django 5.0.6 on 2025-03-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_profile_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img_categoria',
            field=models.ImageField(blank=True, null=True, upload_to='img_categoria/'),
        ),
    ]
